### ISSUE TITLE
PHPUnit extension to highlight tests that perform too many assertions

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/ideas#11]
In a perfect world any given test would perform just one assertion. In reality many tests perform several, but a test that performs more than a handful of assertions can be an indication that the test should be split up or should be fed by a data provider.

I'd like a PHPUnit extension which shows a warning when any single test performs more than a certain, configurable number of assertions. Maybe 3 or 5 is a good default.

**Comment by ozh** [comment]
Something like https://github.com/ozh/phpunit-overassertive ? :)

**Comment by johnbillion** [comment]
Perfect! Thanks Ozh.
