### ISSUE TITLE
Notifications API for WordPress

### ISSUE THREAD

**Issue by johnbillion** [johnbillion/ideas#7]
The core Notifications API project has never gotten off the ground due to lack of time.

Here is a dump of my notes:

----

Different destinations for notifications:
* User
* Email address
* Site administrator
* Network administrator

This ends up being only two types of destination:
* User
* Explicitly an email address not [yet] attached to a user

Potential notification transports:
* Email
	- Sent via default PHP mailer
	- Sent via an email delivery service such as Mandrill / Postmark
* Admin toolbar notification
* SMS
* [Slack](http://aaronrutley.com/send-notifications-from-wordpress-to-slack/)
* Unit test capturing
* Webhook, eg. IFTTT, PushUp
* Push to iOS/Android
* Pushbullet / Join
* IM, XMPP
* Logstash

Need back-compat for:
* Pluggable functions
* Subject filters
* Content filters
* Complete mail filters
* 'disable_X_notification' filters

Need to be able to:
* Filter subject & content
* Disable notifications on per-user basis
* Disable individual notifications
* Disable notifications on a per-type basis
* Produce an admin UI that lists notifications so they can be disabled
* Send HTML and plain text notifications, handle content-type header being filtered
* Allow user to choose notification type (email/Slack)
* Switch notification transport on a per-notification and per notification type basis
* Handle multisite's email template options
* Specify message language
* Provide a nice token system instead of %%USERNAME%%
* Add metadata such as Gmail's inbox actions
* Allow multiple handlers for each notification? eg email and admin toolbar (on-site/off-site notifications?)
* Return success/error state
* Mark a message as critical, ie. fall back to email, can't be disabled
* Handle attachments, mail headers
* Handle all the filters and actions in wp_mail()
* Register a notification ID so it can be disabled or edited from admin UI
* Allow one plugin to implement HTML emails while another implements Mandrill
* Allow a notification to be toggled by admin setting UI and by user preference
* Notification handler state that it can handle attachments
* Support per-site language currently, per-user language in the future
* Grouping of registered notifications for example buddypress so it can provide its own UI.
* Be compatible with existing audit trail plugins such as Simple History and Stream
* Run `wp_specialchars_decode()` on subject and email body automatically? Is it safe to run multiple times?
* Plugins need a way to stop defining wp_mail() and maintain back-compat:
```
if ( function_exists( 'wp_new_notification_api_function' ) && ! function_exists( 'wp_mail' ) ) {
	function wp_mail() {
		// bla
	}
}
```

```
wp_register_notification( array(
	'id'              => 'wp_auto_core_updated',
	'name'            => __( 'Auto core update' ),
	// who this goes to (site admins, users, user_can('publish_posts') ),
	'description'     => '###username### gets replaced with the username',
	'type'            => option/user pref,
	'default_message' => 'Welcome, ###username###'
) );
```

```
wp_register_notification_method( array(
	'id' => 'slack',
) );
```

```
wp_register_something_that_sends_emails( array(
	'id' => 'mandrill',
	// would you ever need more than one of these?
) );
```

```
wp_register_something_that_formats_emails_but_doesnt_send_them( array(
	'id' => 'html_emails',
) );
```

```
wp_register_something_that_formats_emails_but_doesnt_send_them( array(
	'id' => 'gmail_inbox_actions',
) );
```

Going forward:
* wp_mail() could be deprecated by issuing a doing_it_wrong if it's called or if it's declared by a plugin
* other pluggable notification functions need to continue to work as-is
* look at how 2FA handlers are registered
* wp_staticize_emoji_for_email
* site admin and network admin notification types can be converted to user notification types if a corresponding user with that email address exists on the site. need to consider if this is actually desired, ref sites that use a catch-all mailbox for these settings. maybe not a good idea.
* Audit UI and settings where 'email' is mentioned as a notification
* Audit usage of 'From:' header
* Audit plugins in the repo that override wp_mail()
* Look at BuddyPress notifications
* Look at any other plugins with notifications, eg. WooCommerce
* Can we allow deferred (eg. cron-based) notifications? Could be an option or could be done on a per-notification handler basis
* If a custom mail handler is in place it could short circuit all the shitty filters in wp_mail()

`new WP_User_Notification( WP_User $user, array $args )->send()` // recommend specifying notification ID for easier targeting. then it can correlate with a notification setting UI.
`new WP_Email_Notification( $email, array $args )->send()`

Tickets:
* https://make.wordpress.org/core/components/mail/
* https://core.trac.wordpress.org/ticket/24411
* https://core.trac.wordpress.org/ticket/33759
* https://core.trac.wordpress.org/ticket/29069
* Why does WordPress' welcome email even exist?

Plugins that override wp_mail() or do mail-y things:
* https://wordpress.org/plugins/wp-better-emails/
* https://wordpress.org/plugins/postman-smtp/
* https://wordpress.org/plugins/wp-mail-smtp/
* https://wordpress.org/plugins/bnfw/
* Gravity Forms with Slack

----

Allow plugins to register user notification handler. Email handlers specify that they can handle emails too.

**Comment by hedgefield** [comment]
Hi John, I started a trac ticket to tackle this. https://core.trac.wordpress.org/ticket/43484 Looks like you have a ton of ideas already, would love your input!

**Comment by johnbillion** [comment]
https://make.wordpress.org/core/2019/08/05/feature-project-proposal-wp-notify/
